
#CH-230-A
#Makefile.txt
#Lars Schuster
#l.schuster@jacobs-university.de

#Macros
CC = gcc
CFLAGS = -Wall

OBJ = linked_list.o use_linked_list.o

all: do_all

#create both object files and executable
do_all: $(OBJ)
	$(CC) $(CFLAGS) -o use_linked_list $(OBJ)
#create executable
use_linked_list: 
		$(CC) $(CFLAGS) -o use_linked_list $(OBJ)
#create objects
objects: $(OBJ)

#only create use_linked_list object
use_linked_list.o: linked_list.h use_linked_list.c

#only create linked_list object
linked_list.o: linked_list.h linked_list.c

#delete executable and object files
clean:
	rm -f use_linked_list *.o
